// PulseChainCloak Browser - Ad & Tracker Blocklist
// Common advertising and tracking domains (EasyList-style)

const AD_DOMAINS = [
    // Google Ads & Analytics
    'doubleclick.net',
    'googleadservices.com',
    'googlesyndication.com',
    'google-analytics.com',
    'googletagmanager.com',
    'googletagservices.com',
    'pagead2.googlesyndication.com',
    'adservice.google.com',
    'ads.google.com',

    // Facebook/Meta tracking
    'facebook.net',
    'connect.facebook.net',
    'pixel.facebook.com',
    'an.facebook.com',
    'graph.facebook.com',

    // Amazon ads
    'amazon-adsystem.com',
    'aax.amazon-adsystem.com',

    // Common ad networks
    'adnxs.com',
    'adsrvr.org',
    'adform.net',
    'advertising.com',
    'bidswitch.net',
    'casalemedia.com',
    'criteo.com',
    'criteo.net',
    'demdex.net',
    'exelator.com',
    'eyeota.net',
    'mathtag.com',
    'media.net',
    'moatads.com',
    'mookie1.com',
    'openx.net',
    'outbrain.com',
    'pubmatic.com',
    'quantserve.com',
    'rfihub.com',
    'richaudience.com',
    'rubiconproject.com',
    'scorecardresearch.com',
    'sharethrough.com',
    'smartadserver.com',
    'taboola.com',
    'tapad.com',
    'teads.tv',
    'tidaltv.com',
    'tribalfusion.com',
    'turn.com',
    'yieldmo.com',

    // Tracking & Analytics
    'hotjar.com',
    'mixpanel.com',
    'segment.com',
    'segment.io',
    'amplitude.com',
    'fullstory.com',
    'mouseflow.com',
    'crazyegg.com',
    'optimizely.com',
    'newrelic.com',
    'nr-data.net',
    'omtrdc.net',
    'omniture.com',
    'chartbeat.com',
    'chartbeat.net',
    'parsely.com',
    'comscore.com',
    'bluekai.com',
    'krxd.net',
    'rlcdn.com',
    'agkn.com',
    'adsymptotic.com',
    'adroll.com',
    'bounceexchange.com',
    'brealtime.com',
    'contextweb.com',
    'dotomi.com',
    'everesttech.net',
    'imrworldwide.com',
    'intellitxt.com',
    'marchex.io',
    'mxptint.net',
    'nexac.com',
    'serving-sys.com',
    'smaato.net',
    'spotxchange.com',
    'yieldmanager.com',
    'zedo.com',

    // Fingerprinting & Surveillance
    'fingerprintjs.com',
    'ipify.org',

    // Pop-ups & Malware
    'popads.net',
    'popcash.net',
    'propellerads.com',
    'revenuehits.com',
    'adf.ly',
    'shorte.st',
];

// URL path patterns that indicate ads/tracking
const AD_URL_PATTERNS = [
    '/ads/',
    '/ad/',
    '/adserver/',
    '/adframe',
    '/adclick',
    '/adview',
    '/banner/ads',
    '/pagead/',
    '/tracking/',
    '/tracker/',
    '/pixel/',
    '/beacon/',
    '/collect?',
    '/__utm.gif',
    '/piwik.js',
    '/piwik.php',
    '/matomo.js',
    '/matomo.php',
];

export { AD_DOMAINS, AD_URL_PATTERNS };
